### PR TITLE
Add searchable list of all CLA signers

### PR DESCRIPTION
**Pull request by nasamuffin**
Also included is a nasty script to sort & date list as new names are
added.

Signed-off-by: Emily Shaffer <emilyshaffer@google.com>

### CODE REVIEW

**Comment by amboar** [comment]
Can you squash the changes down to one commit and add your SoB tag? Looks okay otherwise. @bradbishop are you okay with this explicit public record of those under the CLA?

Just to clarify I'm not after squashed series in general, but in this case I don't think the changes need to be in separate commits.

**Comment by bradbishop** [comment]
> @bradbishop are you okay with this explicit public record of those under the CLA

I'm not able to come up with any reasons to hide this.

**Comment by bradbishop** [comment]
> I'm not able to come up with any reasons to hide this.
@krtaylor any opinions here?

**Comment by amboar** [comment]
> I'm not able to come up with any reasons to hide this.

The only thing that gave me pause was that the PDFs weren't publicly accessible, but i don't think it's worth hiding either. The list can be approximated by identifying people who have their patches merged.

**Comment by krtaylor** [comment]
The entire list of members that have signed the CLA is usually available to others that have registered, at least with other projects I've been involved with. But since it is required, it is true that everyone going forward that has merged a patch has signed the CLA, as was said. Email is already easily obtained from gerrit so I'd say there is no reason to restrict this info.

**Pull request merged**
