### PR TITLE
Add update-bmc.py

### PR DESCRIPTION
**Pull request by mine260309**
Add this script to update BMC code with phosphor-software-manager.

Tested: Update BMC code on Witherspoon (ubifs) and Romulus (non-ubifs)

Signed-off-by: Lei YU <mine260309@gmail.com>

### CODE REVIEW

**Comment by amboar** [comment]
@mine260309 have you checked out @geissonator 's tools in this area? Particularly [openbmc-sfw](https://github.com/openbmc/openbmc-tools/blob/master/geissonator/openbmc-events/openbmc-sfw).

I'd like to start consolidating functionality we have rather than just continuing to grow everyone's random scripts. Getting all the random scripts in one place was phase 1 of this repo's intent, phase 2 is documentation, and phase 3 is consolidation.

I'm hoping we can skip to phase 3 in this instance and start reducing the bits and pieces we have lying around.

**Comment by mine260309** [comment]
@amboar Indeed, we should make a python module for these common operations.

**Comment by amboar** [comment]
Ideally yes. But before that is it possible for you to just use openbmc-sfw over adding a new tool? If not can you hack openbmc-sfw to do what you need?

**Comment by mine260309** [comment]
Checked the tool, it already covers what I want to do with `update_auto` option.
So we can drop this.

**Pull request closed without merging**
